# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a2cef96e-86be-409d-8bce-2173b32e58cd";
      fsType = "btrfs";
    };

#  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/4e426175-f103-445e-b040-99f680661942";
  boot.initrd.luks.devices = {
    cryptkey = {
      device = "/dev/disk/by-uuid/9f3b93f5-489a-40cf-a732-ebb28e132be0";
    };
    cryptroot = {
      device = "/dev/disk/by-uuid/4e426175-f103-445e-b040-99f680661942";
      keyFile = "/dev/mapper/cryptkey";
    };
    cryptswap = {
      device = "/dev/disk/by-uuid/95f252c7-b834-40af-9960-d22611fd887d";
      keyFile = "/dev/mapper/cryptkey";
    };
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0ED9-C038";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/34a369f3-1033-4e76-8646-38a565badad3"; }
    ];

  nix.maxJobs = lib.mkDefault 12;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
